# Generated by Django 4.1.13 on 2024-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Getting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=34)),
                ('Father_Name', models.CharField(max_length=34)),
                ('Mother_Name', models.CharField(max_length=43)),
            ],
        ),
    ]
