# Generated by Django 4.1.13 on 2024-10-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=18)),
                ('Reason', models.CharField(max_length=18)),
                ('Descrption', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
